-- MySQL Script generated by MySQL Workbench
-- Thu Oct 29 19:11:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simplonBdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simplonBdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simplonBdd` DEFAULT CHARACTER SET utf8 ;
USE `simplonBdd` ;

-- -----------------------------------------------------
-- Table `simplonBdd`.`Etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simplonBdd`.`Etudiant` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `diplome` TINYINT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `prenom_UNIQUE` (`prenom` ASC) VISIBLE,
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplonBdd`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simplonBdd`.`Adresse` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `rue` VARCHAR(45) NOT NULL,
  `numero` INT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `Etudiant_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Adresse_Etudiant_idx` (`Etudiant_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Adresse_Etudiant`
    FOREIGN KEY (`Etudiant_ID`)
    REFERENCES `simplonBdd`.`Etudiant` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplonBdd`.`Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simplonBdd`.`Salle` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplonBdd`.`Professeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simplonBdd`.`Professeur` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `matiere` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE,
  UNIQUE INDEX `prenom_UNIQUE` (`prenom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplonBdd`.`Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simplonBdd`.`Cours` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `heureDebut` DATETIME NULL,
  `heureFin` DATETIME NULL,
  `Salle_ID` INT NOT NULL,
  `Professeur_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Cours_Salle1_idx` (`Salle_ID` ASC) VISIBLE,
  INDEX `fk_Cours_Professeur1_idx` (`Professeur_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Cours_Salle1`
    FOREIGN KEY (`Salle_ID`)
    REFERENCES `simplonBdd`.`Salle` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cours_Professeur1`
    FOREIGN KEY (`Professeur_ID`)
    REFERENCES `simplonBdd`.`Professeur` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplonBdd`.`Participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simplonBdd`.`Participant` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `place` VARCHAR(45) NULL,
  `Etudiant_ID` INT NOT NULL,
  `Cours_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Participant_Etudiant1_idx` (`Etudiant_ID` ASC) VISIBLE,
  INDEX `fk_Participant_Cours1_idx` (`Cours_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Participant_Etudiant1`
    FOREIGN KEY (`Etudiant_ID`)
    REFERENCES `simplonBdd`.`Etudiant` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participant_Cours1`
    FOREIGN KEY (`Cours_ID`)
    REFERENCES `simplonBdd`.`Cours` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
